### PR TITLE
365Inspect v0.0.9 

### PR DESCRIPTION
**Pull request by asterictnl-lvdw**
Dear Soteria,

I would like to share the latest version with a bunch of updates with you and share the changes addings, removals, etc. with you guys. Maybe you guys see some parts as an addition or a fix to your version.

Please consult the CHANGELOG.md for detailed information about the changes. If you need explanation about multiple changes, please let me know. I think another manual review should be needed on this pull-request. 

To Summarize:
- The authentication mechanism is different
- Creation of directory is now fixed properly so a .zip file will be only created of the folder that is created and not of multiple folders
- Added PnP Powershell and Azure Powershell support
- Added functionality to update the modules and remove the modules at startup. 
- Changed the template around to add timestamps, CVS Scores,
- Changes the names of the Inspectors and gave them a label for recognition
- Added 15 new inspectors 
- The HTML / report based on the user choice will be opened after successfully auditing
- Merged the majority of your version with mine
- Removed my duplicates
- Changed the filtering of the inspectors (now based on CVS score instead of risk)
- Added CVS Scores (calculated based on a proper risk analysis per inspector

What still need to be fixed:
- UTF encoding (is not implemented yet)
- The fix for XML and CSV to use a different delimiter
- Removal of Administrator Rights needed, but it might be handy to have due you want to install / update modules

The latest version has been tested on both ISE and Powershell normally. 

Please do let me know if you wish some elaboration or things you would like to see in your version so I can see if I could help you guys out.

~LvdW

### CODE REVIEW

**Comment by ThoughtContagion** [comment]
Hi Leonardo,

This is awesome! Thank you for the submission, a quick glance shows a lot of really great ideas in here. We will begin a thorough review as soon as possible.
One question as a point of clarification, what did you mean by this?

> Creation of directory is now fixed properly so a .zip file will be only created of the folder that is created and not of multiple folders

Were you seeing unrelated directories being added to the reports output path?

**Comment by asterictnl-lvdw** [comment]
> Hi Leonardo,
> 
> This is awesome! Thank you for the submission, a quick glance shows a lot of really great ideas in here. We will begin a thorough review as soon as possible. One question as a point of clarification, what did you mean by this?
> 
> > Creation of directory is now fixed properly so a .zip file will be only created of the folder that is created and not of multiple folders
> 
> Were you seeing unrelated directories being added to the reports output path?

Hello,

Yes. I will explain the process briefly at what I have experienced:
2 situations
When creating the directory as it doesn't exist it created the directory. This is normal activity and that works. (1st time)
The problem is when you choose the same directory again. As your script does not validate if the directory is already created or not it just tries to create the directory again, but fails. No error is given, because you Out-Null it. This is no problem for the code. But when the directory is already filled with a previous audit the part of the code where it creates the .zip file will add all the contents that are included in the folder to the .zip file. So if there were existing audits there it will add them to the .zip. This is not very handy.

What I have done now is as followed:
1. Checking if the path already exists. 
2. If it does exist, checking the permissions and  using a try & catch to create a new path with the orgname_timestamp as directory inside the directory. This to create an unique folder with the contents
3. If the folder did not exist it will first create the root folder and create the orgname_timestamp within the folder. 
4. Any errors are catches and the program will break (quit)

Hope this elaboration is clear to you. If you have any more questions, please let me know. I will be happy to provide more clarification regarding the changes and things I have added.

~LvdW

**Comment by ThoughtContagion** [comment]
> > Hi Leonardo,
> > This is awesome! Thank you for the submission, a quick glance shows a lot of really great ideas in here. We will begin a thorough review as soon as possible. One question as a point of clarification, what did you mean by this?
> > > Creation of directory is now fixed properly so a .zip file will be only created of the folder that is created and not of multiple folders
> > 
> > 
> > Were you seeing unrelated directories being added to the reports output path?
> 
> Hello,
> 
> Yes. I will explain the process briefly at what I have experienced: 2 situations When creating the directory as it doesn't exist it created the directory. This is normal activity and that works. (1st time) The problem is when you choose the same directory again. As your script does not validate if the directory is already created or not it just tries to create the directory again, but fails. No error is given, because you Out-Null it. This is no problem for the code. But when the directory is already filled with a previous audit the part of the code where it creates the .zip file will add all the contents that are included in the folder to the .zip file. So if there were existing audits there it will add them to the .zip. This is not very handy.
> 
> What I have done now is as followed:
> 
> 1. Checking if the path already exists.
> 2. If it does exist, checking the permissions and  using a try & catch to create a new path with the orgname_timestamp as directory inside the directory. This to create an unique folder with the contents
> 3. If the folder did not exist it will first create the root folder and create the orgname_timestamp within the folder.
> 4. Any errors are catches and the program will break (quit)
> 
> Hope this elaboration is clear to you. If you have any more questions, please let me know. I will be happy to provide more clarification regarding the changes and things I have added.
> 
> ~LvdW
> 
> PS: Part of the code:
> 
> ```
> function CreateDirectory(){
>   #Create Output Directory if required
>   if (Test-Path -Path $out_path){
>   Write-Host "Path Exists! Checking Permissions..."
>   try{
>   $newpath = "$out_path\$($org_name)_$(Get-Date -Format "yyyyMMddhhmmss")"
>   New-Item -ItemType Directory -Force -Path $newpath | Out-Null
>   $path = Resolve-Path $out_path
>   return $newpath
>   }catch{
>   Write-Error "Could not create directory" 
>   break
>   }
>   }else{
>   Write-Host "Path does not exist! Creating Directory..."
>   try{
>   New-Item -ItemType Directory -Force -Path $out_path | Out-Null
>   $newpath = "$out_path\$($org_name)_$(Get-Date -Format "yyyyMMddhhmmss")"
>   New-Item -ItemType Directory -Force -Path $newpath | Out-Null
>   $path = Resolve-Path $out_path
>   return $newpath
>   }catch{
>   Write-Error "Could not create Directory! Insufficient Permissions!"
>   break
>   }
>   }
> }
> ```

That makes perfect sense. If we have any other questions come up over the course of the review, we'll ask them here. Thank you!

**Comment by asterictnl-lvdw** [comment]
OK In this version I found a couple of bugs. 

The number of executed inspectors is not pipelined correctly and the startdate is not working correctly. I will fix it and release v0.9.1 on my repo.

**Comment by asterictnl-lvdw** [comment]
Ok I have fixed the issues. v0.1.0 is released with bugfixes. I also fixed an inspector which failed to count the admin roles properly due a MSGraph error.

~LvdW

**Comment by ThoughtContagion** [comment]
Just wanted to provide a status update - we're still in the process of reviewing all the various changes and additions. 👍

**Comment by asterictnl-lvdw** [comment]
> Just wanted to provide a status update - we're still in the process of reviewing all the various changes and additions. 👍

Hello,

Happy to hear that! I am currently fixing some bugs. They will be released in v0.3.0. It are some minor fixes for people who do not have PowerShell configured at all. I happened to stumble upon this problem after my migration to a new fresh OS.

That release is scheduled for tomorrow as the final things are tested today and this morning. 

~LvdW

**Comment by asterictnl-lvdw** [comment]
Update 01-09-2022: I have released v0.3.0 with some bugfixes regarding issues. Thankfully it has been tested on a fresh OS so those bugs will not happen anymore.

Consult the Changelog.md for more information.

~LvdW

**Comment by ThoughtContagion** [comment]
Apologies for the lack of response, our team has been busy.
We're excited to see the release of 365SAT in the coming year, and appreciate your contributions to 365Inspect.
We will continue to review the submitted changes and integrate items that fit our vision with all appropriate attribution.
I will close this PR now as you have a planned release of your tool.
Thank you for being a valuable member of the community!

**Comment by asterictnl-lvdw** [comment]
@ThoughtContagion 

I want to inform M365SAT is up for public testing. If you want to participate and report bugs to me, please do so! Some issues I am aware of. These will be released in the next upcoming release.

https://github.com/asterictnl-lvdw/M365SAT

~LvdW

**Pull request closed without merging**
